# Generated by Django 3.1.3 on 2020-12-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=50)),
                ('total_donation_amount', models.IntegerField(default=0)),
                ('total_spent_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_first_name', models.CharField(max_length=200)),
                ('donor_last_name', models.CharField(max_length=200)),
                ('candidate_first_name', models.CharField(max_length=200)),
                ('candidate_last_name', models.CharField(max_length=200)),
                ('candidate_party', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
