# Generated by Django 3.1.3 on 2020-12-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_auto_20201202_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='candidate_first_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='candidate_last_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='candidate_party',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_first_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_last_name',
        ),
    ]
